name: Deploy

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - uses: actions/checkout@v2
      - run: npm ci
      - shell: bash
        run: chmod +x resetservice.sh
      - shell: bash
        run: ./resetservice.sh
